# Generated by Django 6.0.5 on 2026-05-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('teacher', 'Викладач'), ('starosta', 'Староста')], max_length=10, verbose_name='роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активний')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'користувач',
                'verbose_name_plural': 'користувачі',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='кафедра')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'профіль викладача',
                'verbose_name_plural': 'профілі викладачів',
            },
        ),
        migrations.CreateModel(
            name='StarostaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starostas', to='groups.group', verbose_name='група')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'starosta'}, on_delete=django.db.models.deletion.CASCADE, related_name='starosta_profile', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'профіль старости',
                'verbose_name_plural': 'профілі старост',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
