# Generated by Django 6.0.5 on 2026-05-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='назва')),
                ('course', models.PositiveSmallIntegerField(verbose_name='курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
            ],
            options={
                'verbose_name': 'група',
                'verbose_name_plural': 'групи',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('is_active', models.BooleanField(default=True, verbose_name='активний')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group', verbose_name='група')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенти',
                'ordering': ['full_name'],
                'unique_together': {('full_name', 'group')},
            },
        ),
    ]
