# Generated by Django 6.0.5 on 2026-05-10 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('status', models.CharField(choices=[('PRESENT', 'Присутній'), ('ABSENT', 'Відсутній'), ('EXCUSED', 'Поважна причина'), ('LATE', 'Запізнився')], default='PRESENT', max_length=10, verbose_name='статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='відмітив')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedules.schedule', verbose_name='пара')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='groups.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'відвідування',
                'verbose_name_plural': 'відвідування',
                'ordering': ['date', 'student__full_name'],
                'indexes': [models.Index(fields=['date', 'schedule'], name='attendance__date_1cb817_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx')],
                'unique_together': {('student', 'schedule', 'date')},
            },
        ),
    ]
