# Generated by Django 6.0.5 on 2026-05-10 20:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('start_date', models.DateField(verbose_name='дата початку')),
                ('end_date', models.DateField(verbose_name='дата завершення')),
                ('first_study_week_date', models.DateField(help_text='Понеділок першого навчального тижня. Тиждень 1 = непарний.', verbose_name='дата першого навчального тижня')),
                ('is_active', models.BooleanField(default=False, verbose_name='активний')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестри',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_semester')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('lab', 'Лабораторна'), ('practice', 'Практика')], max_length=10, verbose_name='тип заняття')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота')], verbose_name='день тижня')),
                ('lesson_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='номер пари')),
                ('week_type', models.CharField(choices=[('ODD', 'Непарний'), ('EVEN', 'Парний')], max_length=4, verbose_name='тип тижня')),
                ('start_time', models.TimeField(verbose_name='початок')),
                ('end_time', models.TimeField(verbose_name='кінець')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='groups.group', verbose_name='група')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='викладач')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.semester', verbose_name='семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'розклад',
                'verbose_name_plural': 'розклад',
                'ordering': ['weekday', 'lesson_number'],
                'unique_together': {('group', 'semester', 'weekday', 'lesson_number', 'week_type')},
            },
        ),
    ]
