# Generated by Django 5.2 on 2026-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], help_text='Підгрупа застосовується лише для лабораторних занять.', max_length=1, null=True, verbose_name='підгрупа'),
        ),
    ]
